import 'dotenv/config'

export const {
    NODE_ENV,
    SERVER_PORT,

    JWT_SECRET_SESSION,
    JWT_REFRESH_SESSION,
    JWT_PASSWORD_RECOVERY,
    JWT_ACCESS_EXPIRATION_TIME,
    JWT_REFRESH_REFRESH_EXPIRATION_TIME,
    JWT_ACCOUNT_RECOVERY,

    DB_NAME_DEV,
    DB_USER_DEV,
    DB_PASSWORD_DEV,
    DB_HOST_DEV,
    DB_DIALECT_DEV,
    DB_SCHEMA_DEV,

    DB_SCHEMA_PROD,
    DB_NAME_PROD,
    DB_USER_PROD,
    DB_PASSWORD_PROD,
    DB_HOST_PROD,
    DB_DIALECT_PROD,

    DB_SCHEMA_TEST,
    DB_NAME_TEST,
    DB_USER_TEST,
    DB_PASSWORD_TEST,
    DB_HOST_TEST,
    DB_DIALECT_TEST,

    RESEND_API_KEY,
    ADMIN_EMAIL,
    ADMIN_SMS,

    VONAGE_API_KEY,
    VONAGE_API_SECRET,

    COOKIES_SECRET,
    CSRF_SECRET,

    ENCRYPTION_CONTRACT,
    RECOVERY_ACCOUNT_SKEY,

    PAYPAL_CLIENT_ID,
    PAYPAL_SECRET,

    EMAIL_TEST,
    PHONE_TEST,

    SYSTEM_CURRENCY,

    RABBITMQ_URL,
    EXCHANGE_NAME,
    QUEUE_NAME,
    DLQ_NAME,

    OTLP_TRACES_ENDPOINT,
    OTLP_METRICS_ENDPOINT,

    TRACER_NAME,
} = process.env
