version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:1.51
    container_name: jaeger
    restart: always
    ports:
      - "16686:16686"  # UI de Jaeger
      - "14250:14250"  # OTLP gRPC
      - "14268:14268"  # OTLP HTTP
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      - COLLECTOR_OTLP_ENABLED=true
